version: '3.8'

services:
  # Kafka broker 1
  kafka1:
    image: bitnami/kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9991:9991" # JMX
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qg
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,INTERNAL://:9094,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka1:9094,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_JMX_PORT=9991
      - KAFKA_JMX_HOSTNAME=kafka1
      - EXTRA_ARGS=-javaagent:/etc/kafka/jmx_exporter/jmx_prometheus_javaagent-0.3.1.jar=9991:/etc/kafka/jmx_exporter/kafka-broker.yml
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms1G

    volumes:
      - kafka1-data:/bitnami/kafka
      - ./jmx_exporter:/etc/kafka/jmx_exporter
    networks:
      - kafka-network

  # Kafka broker 2
  kafka2:
    image: bitnami/kafka:latest
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9094:9092"
      - "9992:9992" # JMX
    environment:
      - KAFKA_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qg
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,INTERNAL://:9094,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka2:9094,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_JMX_PORT=9992
      - KAFKA_JMX_HOSTNAME=kafka2
      - EXTRA_ARGS=-javaagent:/etc/kafka/jmx_exporter/jmx_prometheus_javaagent-0.3.1.jar=9992:/etc/kafka/jmx_exporter/kafka-broker.yml
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms1G
    volumes:
      - kafka2-data:/bitnami/kafka
      - ./jmx_exporter:/etc/kafka/jmx_exporter
    networks:
      - kafka-network

  # Kafka broker 3
  kafka3:
    image: bitnami/kafka:latest
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9096:9092"
      - "9993:9993" # JMX
    environment:
      - KAFKA_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qg
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,INTERNAL://:9094,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka3:9094,EXTERNAL://localhost:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_JMX_PORT=9993
      - KAFKA_JMX_HOSTNAME=kafka3
      - EXTRA_ARGS=-javaagent:/etc/kafka/jmx_exporter/jmx_prometheus_javaagent-0.3.1.jar=9993:/etc/kafka/jmx_exporter/kafka-broker.yml
      - KAFKA_HEAP_OPTS=-Xmx1G -Xms1G
    volumes:
      - kafka3-data:/bitnami/kafka
      - ./jmx_exporter:/etc/kafka/jmx_exporter
    networks:
      - kafka-network

  # Kafka-exporter
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    command:
      - "--kafka.server=kafka1:9094"
      - "--kafka.server=kafka2:9094"
      - "--kafka.server=kafka3:9094"
    ports:
      - "9308:9308"
    networks:
      - kafka-network
    restart: always
    depends_on:
      - kafka1
      - kafka2
      - kafka3


  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - kafka-network
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - kafka-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /bitnami/kafka:/bitnami/kafka:ro
    networks:
      - kafka-network
    depends_on:
      - prometheus

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - kafka-network
    depends_on:
      - prometheus

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  prometheus-data:
  grafana-data: