{
 "title": "Update Kafka Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Kafka Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Brokers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_broker_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Controller",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unclean Leader Elections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec{metric_type=\"Count\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Partition Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Request Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(kafka_network_request_per_sec{request=\"Produce\", aggregate=\"OneMinuteRate\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Request Per Sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(kafka_network_request_per_sec{request=\"FetchConsumer\", aggregate=\"OneMinuteRate\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "timeseries",
   "description": "(1-Minute Rate)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_server_messagesinpersec{metric_type=\"OneMinuteRate\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Second",
   "type": "timeseries",
   "description": "(1-Minute Rate)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_server_bytesinpersec{metric_type=\"OneMinuteRate\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Size Balance",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(partition) (kafka_log_log_size{topic!~\"__consumer_offsets|__cluster_metadata|second-topic\"}) / ignoring(partition) group_left sum(kafka_log_log_size{topic!~\"__consumer_offsets|__cluster_metadata|second-topic\"})",
     "legendFormat": "first-topic,partition: {{partition}}"
    },
    {
     "expr": "100 * sum by(partition) (kafka_log_log_size{topic!~\"__consumer_offsets|__cluster_metadata|first-topic\"}) / ignoring(partition) group_left sum (kafka_log_log_size{topic!~\"__consumer_offsets|__cluster_metadata|first-topic\"})",
     "legendFormat": "second-topic,partition: {{partition}}"
    }
   ]
  },
  { "title": "System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"node-exporter:9100\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\", job=\"node-exporter\"} / node_memory_MemTotal_bytes{instance=\"node-exporter:9100\", job=\"node-exporter\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kafka_log_log_size)", "legendFormat": "__auto" }
   ]
  }
 ]
}